name: Build GNSS + Sound Kernel Modules (aarch64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-module:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu make bc flex bison libssl-dev libelf-dev dwarves

    - name: Set environment variables
      run: |
        echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "ARCH=arm64" >> $GITHUB_ENV

    - name: Configure kernel for GNSS and Sound modules
      run: |
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
        scripts/config --enable CONFIG_GNSS
        scripts/config --module CONFIG_GNSS_SERIAL
        scripts/config --module CONFIG_GNSS_SIRF
        scripts/config --module CONFIG_GNSS_UBX
        scripts/config --module CONFIG_GNSS_MTK

        scripts/config --enable CONFIG_SND
        scripts/config --enable CONFIG_SND_SOC
        scripts/config --module CONFIG_SND_SOC_GENERIC_DMAENGINE_PCM
        scripts/config --module CONFIG_SND_SOC_QCOM
        scripts/config --module CONFIG_SND_SOC_MSM8916

        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig

    - name: Build GNSS modules only
      run: |
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- M=drivers/gnss modules -j$(nproc)
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- M=drivers/gnss/serial modules -j$(nproc)

    - name: Build Sound modules only
      run: |
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- M=sound/soc modules -j$(nproc)

    - name: Upload compiled modules
      uses: actions/upload-artifact@v4
      with:
        name: gnss-sound-modules-aarch64
        path: |
          drivers/gnss/*.ko
          drivers/gnss/serial/*.ko
          sound/soc/*.ko
